package utils

type SDG string

const (
	NO_POVERTY                         SDG = "NO_POVERTY"
	ZERO_HUNGER                        SDG = "ZERO_HUNGER"
	HEALTH                             SDG = "HEALTH"
	EDUCATION_QUALITY                  SDG = "EDUCATION_QUALITY"
	GENDER_EQUALITY                    SDG = "GENDER_EQUALITY"
	WATER_SANITATION                   SDG = "WATER_SANITATION"
	ENERGY                             SDG = "ENERGY"
	DECENT_WORK                        SDG = "DECENT_WORK"
	INDUSTRY_INNOVATION_INFRASTRUCTURE SDG = "INDUSTRY_INNOVATION_INFRASTRUCTURE"
	REDUCED_INEQUALITIES               SDG = "REDUCED_INEQUALITIES"
	SUSTAINABLE_CITIES_COMMUNITIES     SDG = "SUSTAINABLE_CITIES_COMMUNITIES"
	RESPONSIBLE_CONSUMPTION_PRODUCTION SDG = "RESPONSIBLE_CONSUMPTION_PRODUCTION"
	CLIMATE_ACTION                     SDG = "CLIMATE_ACTION"
	LIFE_BELOW_WATER                   SDG = "LIFE_BELOW_WATER"
	LIFE                               SDG = "LIFE"
	PEACE_JUSTICE                      SDG = "PEACE_JUSTICE"
	GOALS_PARTNERSHIPS                 SDG = "GOALS_PARTNERSHIPS"
	OTHER                              SDG = "OTHER"
)

var SocialCausesSDGMapping = map[string]SDG{
	"SOCIAL":                        REDUCED_INEQUALITIES,
	"POVERTY":                       NO_POVERTY,
	"HOMELESSNESS":                  REDUCED_INEQUALITIES,
	"HUNGER":                        ZERO_HUNGER,
	"HEALTH":                        HEALTH,
	"SUBSTANCE_ABUSE":               HEALTH,
	"MENTAL":                        HEALTH,
	"BULLYING":                      HEALTH,
	"SECURITY":                      PEACE_JUSTICE,
	"EDUCATION":                     EDUCATION_QUALITY,
	"GENDER_EQUALITY":               GENDER_EQUALITY,
	"GENDER_BASED_VIOLENCE":         GENDER_EQUALITY,
	"SEXUAL_VIOLENCE":               GENDER_EQUALITY,
	"DOMESTIC_VIOLENCE":             GENDER_EQUALITY,
	"WATER_SANITATION":              LIFE_BELOW_WATER,
	"SUSTAINABLE_ENERGY":            ENERGY,
	"DECENT_WORK":                   DECENT_WORK,
	"INEQUALITY":                    REDUCED_INEQUALITIES,
	"MINORITY":                      REDUCED_INEQUALITIES,
	"MULTICULTURALISM":              REDUCED_INEQUALITIES,
	"DIVERSITY_INCLUSION":           REDUCED_INEQUALITIES,
	"INDIGENOUS_PEOPLES":            REDUCED_INEQUALITIES,
	"DISABILITY":                    REDUCED_INEQUALITIES,
	"LGBTQI":                        REDUCED_INEQUALITIES,
	"REFUGEE":                       REDUCED_INEQUALITIES,
	"MIGRANTS":                      REDUCED_INEQUALITIES,
	"ORPHANS":                       REDUCED_INEQUALITIES,
	"CHILD_PROTECTION":              REDUCED_INEQUALITIES,
	"COMMUNITY_DEVELOPMENT":         SUSTAINABLE_CITIES_COMMUNITIES,
	"DEPOPULATION":                  SUSTAINABLE_CITIES_COMMUNITIES,
	"OVERPOPULATION":                SUSTAINABLE_CITIES_COMMUNITIES,
	"HUMAN_RIGHTS":                  REDUCED_INEQUALITIES,
	"SUSTAINABILITY":                SUSTAINABLE_CITIES_COMMUNITIES,
	"RESPONSIBLE_CONSUMPTION":       RESPONSIBLE_CONSUMPTION_PRODUCTION,
	"CLIMATE_CHANGE":                CLIMATE_ACTION,
	"NATURAL_DISASTERS":             CLIMATE_ACTION,
	"BIODIVERSITY":                  REDUCED_INEQUALITIES,
	"ANIMAL_RIGHTS":                 LIFE,
	"ARMED_CONFLICT":                PEACE_JUSTICE,
	"PEACEBUILDING":                 PEACE_JUSTICE,
	"DEMOCRACY":                     PEACE_JUSTICE,
	"CIVIC_ENGAGEMENT":              PEACE_JUSTICE,
	"JUSTICE":                       PEACE_JUSTICE,
	"GOVERNANCE":                    PEACE_JUSTICE,
	"CRIME_PREVENTION":              PEACE_JUSTICE,
	"CORRUPTION":                    PEACE_JUSTICE,
	"OTHER":                         OTHER,
	"RURAL_DEVELOPMENT":             SUSTAINABLE_CITIES_COMMUNITIES,
	"VEGANISM":                      RESPONSIBLE_CONSUMPTION_PRODUCTION,
	"BLACK_LIVES_MATTER":            REDUCED_INEQUALITIES,
	"ISLAMOPHOBIA":                  REDUCED_INEQUALITIES,
	"ANTI_SEMITISM":                 REDUCED_INEQUALITIES,
	"ABORTION":                      HEALTH,
	"EUTHANASIA":                    HEALTH,
	"NEURODIVERSITY":                REDUCED_INEQUALITIES,
	"SUSTAINABLE_COMMUNITIES":       SUSTAINABLE_CITIES_COMMUNITIES,
	"BIODIVERSITY_LIFE_BELOW_WATER": LIFE_BELOW_WATER,
	"PEACE_JUSTICE":                 PEACE_JUSTICE,
	"COLLABORATION_FOR_IMPACT":      GOALS_PARTNERSHIPS,
	"INNOVATION":                    INDUSTRY_INNOVATION_INFRASTRUCTURE,
}

func GetSDG(socialCause string) SDG {
	if sdg, ok := SocialCausesSDGMapping[socialCause]; ok {
		return sdg
	}
	return OTHER
}
